name: 'AI Code Review'
description: 'GitHub Action for AI-assisted code reviews using ChatGPT'
author: 'Your Name'
branding:
  icon: 'code'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for accessing the repository'
    required: true
  openai-api-key:
    description: 'OpenAI API key for using ChatGPT'
    required: true

outputs:
  review-results:
    description: 'JSON string containing review comments with file paths and line numbers'

runs:
  using: 'node20'
  main: 'dist/index.js' 