# AI Code Review Configuration

# Global excludes - These files will always be excluded
excludeFiles:
  - '**/node_modules/**'
  - '**/dist/**'
  - '**/build/**'
  - '**/*.min.js'
  - '**/*.test.ts'
  - '**/*.spec.ts'

# Review rules - Each rule specifies what files to include and what to look for
rules:
  - include:
      - '**/*.ts'
      - '**/*.tsx'
    prompt: >
      Review this TypeScript code focusing on type safety, proper interface usage, 
      and adherence to TypeScript best practices. Look for potential null/undefined issues, 
      incorrect typing, and opportunities to improve type definitions.

  - include:
      - '**/*.js'
      - '**/*.jsx'
    prompt: >
      Review this JavaScript code focusing on potential runtime errors, variable scope issues,
      and modern JavaScript practices. Check for proper error handling, async/await usage,
      and potential memory leaks.

  - include:
      - '**/*.py'
    prompt: >
      Review this Python code focusing on PEP 8 compliance, proper exception handling,
      and Pythonic approaches. Check for inefficient algorithms, unnecessary complexity,
      and security vulnerabilities like SQL injection or unsafe eval.

  - include:
      - '**/*.go'
    prompt: >
      Review this Go code focusing on concurrency patterns, error handling, and idiomatic Go.
      Look for proper resource management, potential race conditions, and inefficient memory usage.

  - include:
      - '**/*.java'
      - '**/*.kt'
    prompt: >
      Review this Java/Kotlin code focusing on OOP principles, exception handling, and performance.
      Check for memory leaks, thread safety issues, and opportunities for improved design patterns.

  - include:
      - '**/*.rb'
    prompt: >
      Review this Ruby code focusing on Ruby idioms, metaprogramming concerns, and Ruby best practices.
      Look for potential performance bottlenecks and areas where the code could be more elegant.

  - include:
      - '**/*.sql'
    prompt: >
      Review this SQL code focusing on query performance, proper indexing suggestions,
      and potential SQL injection vulnerabilities. Check for unnecessarily complex queries
      and opportunities for optimization.

  - include:
      - '**/Dockerfile'
      - '**/*.dockerfile'
      - '**/docker-compose.yml'
    prompt: >
      Review this Docker configuration focusing on security best practices, image size optimization,
      and efficient layer caching. Look for potential security vulnerabilities and inefficient patterns. 