# AI Code Review Configuration
# This action reviews only the code changes in pull requests,
# but also provides file context for better analysis

# AI model settings
model: 'gpt-4-turbo'
commentThreshold: 50
maxTokens: 4096
temperature: 0.7

# Global excludes - These files will always be excluded
excludeFiles:
  - '**/node_modules/**'
  - '**/dist/**'
  - '**/build/**'
  - '**/*.min.js'
  - '**/*.test.ts'
  - '**/*.spec.ts'
  - '**/*.yml'
  - '**/*.yaml'
  - '.github/**/*.yml'
  - '.github/**/*.yaml'

# Review rules - Each rule specifies what files to include and what to look for
# Each prompt should focus on reviewing specific CHANGES rather than entire files
rules:
  - include:
      - '**/*.ts'
      - '**/*.tsx'
    prompt: >
      Review these TypeScript code CHANGES focusing on type safety, proper interface usage, 
      and adherence to TypeScript best practices. Look for potential null/undefined issues, 
      incorrect typing, and opportunities to improve type definitions.

  - include:
      - '**/*.js'
      - '**/*.jsx'
    prompt: >
      Review these JavaScript code CHANGES focusing on potential runtime errors, variable scope issues,
      and modern JavaScript practices. Check for proper error handling, async/await usage,
      and potential memory leaks.

  - include:
      - '**/*.py'
    prompt: >
      Review these Python code CHANGES focusing on PEP 8 compliance, proper exception handling,
      and Pythonic approaches. Check for inefficient algorithms, unnecessary complexity,
      and security vulnerabilities like SQL injection or unsafe eval.

  - include:
      - '**/*.go'
    prompt: >
      Review these Go code CHANGES focusing on concurrency patterns, error handling, and idiomatic Go.
      Look for proper resource management, potential race conditions, and inefficient memory usage.

  - include:
      - '**/*.java'
      - '**/*.kt'
    prompt: >
      Review these Java/Kotlin code CHANGES focusing on OOP principles, exception handling, and performance.
      Check for memory leaks, thread safety issues, and opportunities for improved design patterns.

  - include:
      - '**/*.rb'
    prompt: >
      Review these Ruby code CHANGES focusing on Ruby idioms, metaprogramming concerns, and Ruby best practices.
      Look for potential performance bottlenecks and areas where the code could be more elegant.

  - include:
      - '**/*.sql'
    prompt: >
      Review these SQL code CHANGES focusing on query performance, proper indexing suggestions,
      and potential SQL injection vulnerabilities. Check for unnecessarily complex queries
      and opportunities for optimization.

  - include:
      - '**/Dockerfile'
      - '**/*.dockerfile'
      - '**/docker-compose.yml'
    prompt: >
      Review these Docker configuration CHANGES focusing on security best practices, image size optimization,
      and efficient layer caching. Look for potential security vulnerabilities and inefficient patterns. 