# AI Code Review Configuration

# Files to include in the review (glob patterns)
includeFiles:
  - '**/*.ts'
  - '**/*.js'
  - '**/*.tsx'
  - '**/*.jsx'
  - '**/*.py'
  - '**/*.go'
  - '**/*.java'
  - '**/*.rb'

# Files to exclude from the review (glob patterns)
excludeFiles:
  - '**/node_modules/**'
  - '**/dist/**'
  - '**/build/**'
  - '**/*.test.ts'
  - '**/*.spec.ts'
  - '**/*.min.js'

# AI prompt rules
promptRules:
  # System prompt for the AI
  systemPrompt: >
    You are an expert code reviewer with extensive experience in software development.
    Analyze the code changes and provide constructive feedback.
    Focus on code quality, potential bugs, security issues, performance concerns, and best practices.
    Be specific and actionable in your feedback, explaining why a change is recommended.
    For each issue, rate its severity (low, medium, high) and provide a suggested fix if possible.

  # User prompt template for the AI (will be filled with code content)
  userPrompt: >
    Please review the following code changes:

    {code}

    Please provide specific, actionable feedback with reasoning.
    For each issue, include a severity rating and a suggested fix if possible.

# Model configuration
model: 'gpt-4-turbo'  # The OpenAI model to use
commentThreshold: 50   # Minimum confidence threshold (0-100) for posting comments
maxTokens: 4096        # Maximum tokens to use per API call
temperature: 0.7       # Temperature for the AI generation (0.0-1.0) 