name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Check for uncommitted changes
        id: check-changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Changes detected after build. Please run 'npm run build' and commit the changes."
            git status
            git diff
            exit 1
          fi 